pipeline {
  agent any
  stages {
    stage('Checkout') { steps { checkout scm } }
    stage('Build + Unit/Integration Tests') { steps { sh 'mvn -B clean verify' } }
    stage('Package') { steps { sh 'mvn -B -DskipTests package' } }
    stage('Docker Image') { steps { sh 'docker build -t ia-app:${BUILD_NUMBER} .' } }
  }
  post { always { junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml' } }
}
